### ISSUE TITLE
[BUG] Search does not seem to be including results from third party portals.

### ISSUE THREAD

**Issue by Absoblogginlutely** [adamfowlerit/msportals.io#207] opened 2022-08-24 14:20 UTC
## Describe the bug ##

Search does not seem to be searching the 3rd party sites.

## To Reproduce ##

Search for "safe" or "Message" Neither the safe links decoder or the Message Header Analyzer links from the 3rd party portals show up in the search results.
Have used multiple machines and get the same results. Edge and Edge Dev.

## Expected behavior ##
Search results should include results from all sections.

## Screenshots ##
Listing of 3rd party links.
![Screenshot - 8_24_2022 , 10_16_15 AM](https://user-images.githubusercontent.com/21364480/186442503-ebd1a1a9-f111-4e5d-b5b3-655cc9278c9b.png)
Search results
![Screenshot - 8_24_2022 , 10_10_12 AM](https://user-images.githubusercontent.com/21364480/186442526-25a62932-0431-43ad-93ca-aacca22398da.png)

## Desktop (please complete the following information) ##

- OS: Windows 11
- Browser Edge and Edge Dev
- Version 06.0.1349.1

**Comment by yaki3355** [comment] 2022-08-25 11:00
Hey @Absoblogginlutely 

Can you try again?
It works for me:
![image](https://user-images.githubusercontent.com/44410275/186647057-ebf0317f-8d2b-4b3a-8b94-e229bd0b6a28.png)

OS: Windows 10
Browser: Edge

**Comment by AHelsby** [comment] 2022-08-26 12:04
So it's probably user error :-)
I replicated the issue on my mobile phone this morning and realised that the search is only searching on the current "tab" (ie the Home section only) instead of all the sections.
It works if I switch to end user tab and then search.

Therefore, could/should this be a feature request to search across all the tabs rather than just the active one?

**Comment by Computer-Tsu** [comment] 2022-11-13 01:09
I need to change from Home to 3rd party for "ten" to search match 
tenant.

**Comment by PsychoData** [comment] 2023-12-16 07:32
Agreed - I've thought about that as well. 
Searching ALL of the pages at once would be preferable. 
And I was thinking something like turning on which Cloud/Government Levels you want to see results from, as well. 
For example 
- [ ] Azure Commercial 
- [ ] GCC 
- [X] GCC High
- [ ] DoD 

It would definitely need a pretty MAJOR redesign of things though, and I started a Project trying to go that direction ( https://github.com/adamfowlerit/msportals.io/projects/2)  a LONG time ago, but haven't gotten back to it yet. 

However, as things are currently running, this is not a bug, just a misunderstanding of how the pages and search were working, so I'm going to close this out for now.

**Comment by PsychoData** [comment] 2023-12-16 07:34
Current site functionality is working as intended. 
May be fixed in the future but re-architecting the site

**Closed by PsychoData** 2023-12-16 07:34 UTC
Labels: bug
